Repository woocommerce/pinterest-for-woocommerce, pull requests merged in 2022-11, with the labels that each got.

#630 Finalise copy after suggestions.
  assets/source/setup-guide/app/components/TermsAndConditionsModal.js
Labels: changelog: none

#631 Add update version for ads credit.
  src/PluginUpdate.php
Labels: changelog: none

#610 Back off mechanism for create merchant
  src/Merchants.php
Labels: type: bug, changelog: fix

#635 Add promo information to the readme.txt
  readme.txt
Labels: type: enhancement, changelog: add

#636 release/1.2.6
  changelog.txt
  package-lock.json
  package.json
  pinterest-for-woocommerce.php
  readme.txt
Labels: changelog: none

#637 Merge release/1.2.6 to trunk
  changelog.txt
  package-lock.json
  package.json
  pinterest-for-woocommerce.php
  readme.txt
  src/Merchants.php
Labels: changelog: none

#593 Cast settings to array to prevent fatal errors
  src/TrackerSnapshot.php
Labels: type: bug, changelog: fix

#639 Use min instead of max
  src/Merchants.php
Labels: type: bug, changelog: fix

#640 Fix - 510: Avoid splitting strings for translations
  assets/source/catalog-sync/components/OnboardingModals/OnboardingAdsModal.js
  assets/source/setup-guide/app/steps/SetupTracking.js
Labels: type: bug, changelog: fix
