Repository woocommerce/pinterest-for-woocommerce, pull requests merged in 2023-05, with the labels that each got.

#750 Release/1.2.21 (into trunk)
  changelog.txt
  package-lock.json
  package.json
  pinterest-for-woocommerce.php
  readme.txt
Labels: changelog: none

#751 Release/1.2.21 (merge trunk to develop)
  changelog.txt
  package-lock.json
  package.json
  pinterest-for-woocommerce.php
  readme.txt
Labels: changelog: none

#740 Redirect to the new endpoint.
  class-pinterest-for-woocommerce.php
Labels: type: enhancement, changelog: none

#744 Add/intercept v5 connect data
  class-pinterest-for-woocommerce.php
  src/API/Auth.php
  src/API/Base.php
  tests/Unit/TasksTest.php
  tests/Unit/TrackerSnapshotTest.php
Labels: type: enhancement, changelog: add

#747 Save connection info data.
  class-pinterest-for-woocommerce.php
  src/API/Auth.php
Labels: type: enhancement, changelog: add, changelog: none

#737 Fix/remove feed file config during uninstall procedure.
  uninstall.php
Labels: type: bug, priority: high, impact: high, changelog: fix

#756 Add Access Token refresh action.
  class-pinterest-for-woocommerce.php
  src/RefreshToken.php
  tests/Unit/PinterestForWoocommerceTest.php
  tests/Unit/RefreshTokenTest.php
Labels: type: enhancement, changelog: add

#762 Connection flow not redirection the wizard view
  class-pinterest-for-woocommerce.php
  src/API/Auth.php
  src/API/Base.php
Labels: type: bug, changelog: fix

#754 Integration with WooCommerce multichannel marketing dashboard
  class-pinterest-for-woocommerce.php
  src/API/FeedIssues.php
  src/API/FeedState.php
  src/FeedStatusService.php
  src/Feeds.php
  src/MultichannelMarketing/MarketingChannelRegistrar.php
  src/MultichannelMarketing/PinterestChannel.php
  src/Notes/Collection/CatalogSyncErrors.php
Labels: type: enhancement
