Repository woocommerce/pinterest-for-woocommerce, pull requests merged in 2023-01, with the labels that each got.

#647 Add node and npm version restriction to the project.
  .npmrc
Labels: type: enhancement, changelog: add

#657 Release 1.2.8 - merging release branch to trunk
  .npmrc
  changelog.txt
  package-lock.json
  package.json
  pinterest-for-woocommerce.php
  readme.txt
  src/API/FeedIssues.php
Labels: changelog: none

#658 Release 1.2.8 - merging trunk to develop
  changelog.txt
  package-lock.json
  package.json
  pinterest-for-woocommerce.php
  readme.txt
Labels: changelog: none

#662 Add backlog automation
  .github/workflows/backlog-automation.yml
Labels: type: enhancement, changelog: add

#660 Add additional parameters into WC tracker for Pinterest
  src/FeedFileOperations.php
  src/FeedGenerator.php
  src/FeedRegistration.php
  src/ProductFeedStatus.php
  src/ProductSync.php
  src/TrackerSnapshot.php
  tests/Unit/FeedFileOperationsTest.php
  tests/Unit/FeedGeneratorTest.php
  tests/Unit/ProductFeedStatusTest.php
  tests/Unit/TrackerSnapshotTest.php
Labels: type: enhancement, changelog: add

#648 Disable save button if chrome extension is detected
  assets/source/js/pinterest-for-woocommerce-save-button.js
  src/SaveToPinterest.php
Labels: type: bug, changelog: fix

#634 Implement 426, Pull ads supported countries from the api.
  includes/class-pinterest-for-woocommerce-ads-supported-countries.php
  src/API/Base.php
Labels: type: enhancement, changelog: add

#675 Doc/add include exluce filters to docs
  docs/testing-flows.md
Labels: type: documentation, changelog: doc
