Repository woocommerce/pinterest-for-woocommerce, pull requests merged in 2024-03, with the labels that each got.

#920 Send notification email when V5 update procedure fails.
  src/API/TokenExchangeV3ToV5.php
  src/Notes/TokenExchangeFailure.php
  src/PluginUpdate.php
Labels: changelog: none, changelog: update

#925 922 retry oauth
  class-pinterest-for-woocommerce.php
  src/API/Auth.php
  src/Notes/TokenExchangeFailure.php
  src/PluginUpdate.php
  uninstall.php
Labels: changelog: none

#932 Delete Pinterest API version during uninstall procedure.
  uninstall.php
Labels: changelog: none

#933 Updates the readme.txt to meet WordPress requirements
  readme.txt
Labels: changelog: update

#940 Fix logger::log dockblock param name.
  src/Logger.php
Labels: type: bug, changelog: fix

#939 Use options and not transients for feed status manipulation.
  src/PluginUpdate.php
  src/ProductFeedStatus.php
Labels: priority: high, changelog: update

#949 Fix add to cart capi event.
  src/Tracking/Tag.php
Labels: type: bug, changelog: fix

#953 Include em in user data.
  src/Tracking/Conversions.php
Labels: type: enhancement, changelog: add

#954 Match feed url when looking for feeds.
  src/FeedRegistration.php
  src/Feeds.php
Labels: type: enhancement, changelog: add

#957 Fix feed_creation cache key calculation.
  src/Feeds.php
Labels: type: bug, changelog: fix

#959 Always add processing status to results.
  src/API/FeedState.php
Labels: type: enhancement, changelog: add

#961 Decouple feed processing from setup status.
  src/API/FeedState.php
Labels: type: bug, changelog: fix

#966 Log CAPI event only once on error.
  src/Tracking/Conversions.php
Labels: changelog: none

#968 Remove category_name from view_category event.
  src/Tracking/Conversions.php
Labels: changelog: none

#963 Fix small issues found while looking at the file.
  class-pinterest-for-woocommerce.php
Labels: type: bug, changelog: fix

#969 Fix unit tests.
  tests/Unit/Tracking/ConversionsTest.php
Labels: type: bug, changelog: fix

#970 Cache processing_results endpoint response
  src/API/APIV5.php
Labels: changelog: none

#971 Fix bad typo in TokenExchangeV3ToV5.php
  src/API/TokenExchangeV3ToV5.php
Labels: type: bug, changelog: fix, changelog: none

#972 Fix refresh token response log message.
  src/RefreshToken.php
Labels: type: bug, changelog: fix, changelog: tweak

#976 Fix translators strings for Error message.
  src/API/AdvertiserConnect.php
  src/API/Base.php
Labels: changelog: none

#975 Add Twenty Twenty-Four compatibility.
  assets/source/sass/frontend/pinterest-for-woocommerce-pins.scss
Labels: changelog: none
