Repository woocommerce/pinterest-for-woocommerce, pull requests merged in 2024-05, with the labels that each got.

#1012 Release v1.4.1
  .github/workflows/php-cs-on-changes.yml
  .github/workflows/php-unit-tests.yml
  assets/source/setup-guide/app/components/SyncSettings/index.js
  assets/source/setup-guide/app/style.scss
  changelog.txt
  class-pinterest-for-woocommerce.php
  includes/class-pinterest-for-woocommerce-frontend-assets.php
  pinterest-for-woocommerce.php
  readme.txt
  src/API/AdvertiserConnect.php
  src/API/Auth.php
  src/AdCredits.php
  src/Billing.php
  src/Heartbeat.php
  src/PinterestApiException.php
  src/ProductSync.php
  src/RefreshToken.php
  src/Tracking.php
  src/Tracking/Conversions.php
  tests/Unit/HeartbeatTest.php
  tests/Unit/PinterestForWoocommerceTest.php
  tests/Unit/RefreshTokenTest.php
  tests/Unit/Tracking/ConversionsTest.php
Labels: changelog: none

#1015 Don't sync aems when tracking is not enabled.
  src/PinterestSyncSettings.php
  tests/Unit/Api/SyncSettingsTest.php
Labels: type: enhancement, changelog: add, changelog: none

#1016 Fix indentation in PinterestSyncSettings
  src/PinterestSyncSettings.php
Labels: type: bug, changelog: fix, changelog: none

#1018 Adds WooCommerce as a dependency to the plugin header
  pinterest-for-woocommerce.php
Labels: type: enhancement, changelog: add

#1019 Revert woo.com → woocommerce.com in URLs
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  README.md
  TRACKING.md
  composer.json
  docs/testing-flows.md
  pinterest-for-woocommerce.php
  readme.txt
  src/AdCredits.php
  src/MultichannelMarketing/PinterestChannel.php
Labels: type: documentation, changelog: tweak

#826 Adds compat checker for versioning and compatibility
  class-pinterest-for-woocommerce.php
  composer.json
  composer.lock
Labels: type: enhancement, changelog: add
