Repository woocommerce/pinterest-for-woocommerce, pull requests merged in 2024-04, with the labels that each got.

#981 Release v1.4.0
  changelog.txt
  class-pinterest-for-woocommerce.php
  package-lock.json
  pinterest-for-woocommerce.php
  readme.txt
  src/API/APIV5.php
  src/API/Auth.php
  src/API/Base.php
  src/API/DomainVerification.php
  src/API/FeedIssues.php
  src/API/FeedState.php
  src/API/TokenExchangeV3ToV5.php
  src/FeedStatusService.php
  src/Feeds.php
  src/Notes/TokenExchangeFailure.php
  src/PluginUpdate.php
  src/RefreshToken.php
  src/Tracking.php
  src/Tracking/Conversions.php
  src/Tracking/Data/None.php
  src/Tracking/Data/Product.php
  src/Tracking/Data/Search.php
  src/Tracking/Data/User.php
  src/Tracking/Tag.php
  src/Tracking/Tracker.php
  tests/Unit/Api/APIV5Test.php
  tests/Unit/Api/AdvertiserConnectTest.php
  tests/Unit/Api/AdvertisersTest.php
  tests/Unit/Api/DomainVerificationTest.php
  tests/Unit/Api/HealthTest.php
  tests/Unit/Api/SettingsTest.php
  tests/Unit/Api/SyncSettingsTest.php
  tests/Unit/Api/TagsTest.php
Labels: changelog: none

#987 Fix typo.
  src/API/Auth.php
Labels: type: bug, changelog: fix

#997 Fix/fetch correct coupons information
  src/AdCredits.php
Labels: type: bug, changelog: fix, changelog: none

#995 Update/error cases handling for discounts
  class-pinterest-for-woocommerce.php
  src/API/AdvertiserConnect.php
  src/AdCredits.php
  src/Billing.php
  src/PinterestApiException.php
Labels: changelog: none, changelog: update

#1002 Tidy __class__ to proper __CLASS__
  src/ProductSync.php
Labels: category: refactor, changelog: none

#986 Fix tooltip UI issue in Settings page
  assets/source/setup-guide/app/components/SyncSettings/index.js
  assets/source/setup-guide/app/style.scss
Labels: changelog: fix

#984 Update pinit.js script import to match with Pinterest documentation
  includes/class-pinterest-for-woocommerce-frontend-assets.php
Labels: changelog: update

#1001 Adding missing Order ID into `custom_data` array for Checkout CAPI event.
  src/Tracking.php
  src/Tracking/Conversions.php
  tests/Unit/Tracking/ConversionsTest.php
Labels: type: bug, changelog: fix
