Repository woocommerce/pinterest-for-woocommerce, pull requests merged in 2025-03, with the labels that each got.

#1109 Fixes PHP 8.4 deprecated warnings
  src/View/PHPView.php
  src/View/View.php
Labels: type: enhancement, changelog: add

#1108 Replacing `get_locale()` with `WPLANG` option for feed registration.
  src/LocaleMapper.php
  tests/Unit/LocaleMapperTest.php
Labels: type: bug, changelog: fix

#1110 Feed status data missing
  src/FeedStatusService.php
Labels: type: bug, changelog: fix

#1113 Release/1.4.17 - `trunk` to `develop`
  changelog.txt
  class-pinterest-for-woocommerce.php
  package-lock.json
  package.json
  pinterest-for-woocommerce.php
  readme.txt
  src/WPConsentAPI.php
Labels: changelog: none
